"""add product rejection reason

Revision ID: 0aaaba976a85
Revises: f78591994e25
Create Date: 2026-10-03 20:19:42.872695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaaba976a85'
down_revision = 'f78591994e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
