"""simulated payment details

Revision ID: 94a3737fb60e
Revises: f0dea35dbe1b
Create Date: 2026-10-03 21:14:44.756255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a3737fb60e'
down_revision = 'f0dea35dbe1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_detail', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gateway_ref', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('settle_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('settle_at')
        batch_op.drop_column('attempts')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('gateway_ref')
        batch_op.drop_column('reference')
        batch_op.drop_column('method_detail')

    # ### end Alembic commands ###
