"""crypto payment quote fields

Revision ID: bbb4a059d404
Revises: 94a3737fb60e
Create Date: 2026-10-03 21:36:19.903435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb4a059d404'
down_revision = '94a3737fb60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('contract_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.create_unique_constraint('uq_crypto_payments_payment_id', ['payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_crypto_payments_payment_id', type_='unique')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('contract_address')
        batch_op.drop_column('seller_address')

    # ### end Alembic commands ###
