"""notification url and auction ending flag

Revision ID: f0dea35dbe1b
Revises: 0aaaba976a85
Create Date: 2026-10-03 21:05:00.556233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0dea35dbe1b'
down_revision = '0aaaba976a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ending_notified', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_column('ending_notified')

    # ### end Alembic commands ###
